name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os:  [macOS-latest, ubuntu-latest]
        goversion: ['1.20', '1.21', '1.22']
    steps:

    - name: Set up Go ${{matrix.goversion}} on ${{matrix.os}}
      uses: actions/setup-go@v5
      with:
        go-version: ${{matrix.goversion}}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4
    
    - name: gofmt
      run: |
        [[ -z $(gofmt -l $(find . -name '*go') ) ]]

    - name: Get dependencies
      run: go mod download

    - name: Vet
      run: go vet -mod=readonly ./...
      
    - name: Test
      run: go test -mod=readonly ./...
    
    - name: Race Test
      run: go test -race -mod=readonly -v -count 2 ./...
